version: "3.8"
services:
  messaging-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    platform: linux/arm64

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
