openapi: 3.1.0
info:
  title: Messaging Service API
  version: "1.0"
servers:
  - url: http://localhost:3000
paths:
  /messages:
    post:
      summary: Send a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
      responses:
        "200":
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: Bad Request
  /chats/{chatId}/messages:
    get:
      summary: Get chat messages
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
        "400":
          description: Bad Request
  /messages/{messageId}/status:
    put:
      summary: Update message status
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateStatusRequest"
      responses:
        "204":
          description: Message status updated successfully
        "400":
          description: Bad Request
  /users/{userId}/chats:
    get:
      summary: List chats for a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of chats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Chat"
        "400":
          description: Bad Request
components:
  schemas:
    SendMessageRequest:
      type: object
      properties:
        chatId:
          type: integer
        senderId:
          type: integer
        content:
          type: string
      required:
        - chatId
        - senderId
        - content
    Message:
      type: object
      properties:
        id:
          type: integer
        chatId:
          type: integer
        senderId:
          type: integer
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - sent
            - delivered
            - read
            - failed
      required:
        - id
        - chatId
        - senderId
        - content
        - timestamp
        - status
    UpdateStatusRequest:
      type: object
      properties:
        status:
          type: string
          enum:
            - sent
            - delivered
            - read
            - failed
      required:
        - status
    Chat:
      type: object
      properties:
        id:
          type: integer
        participant1Id:
          type: integer
        participant2Id:
          type: integer
        metadata:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - participant1Id
        - participant2Id
        - createdAt
